#
# Blog Settings
#

title: blog.pagesd.info
author: michel


#
# Jekyll Settings
#

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

feed:
  path: atom.xml
