#
# Blog Settings
#

title: blog.pagesd.info
author: michel
lang: fr-FR


#
# Jekyll Settings
#

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

feed:
  path: atom.xml

kramdown:
  syntax_highlighter_opts:
    disable : true


# Pour exclure certains trucs du sitemap.xml
# (on peut aussi ajouter "sitemap: false" dans le front-matter des posts/pages à exclure)
defaults:
  - scope:
      path: "git-hub-tips/**"
    values:
      sitemap:         false
  - scope:
      path: "public/**"
    values:
      sitemap:         false
