#
# Blog Settings
#

title: blog.pagesd.info
author: michel
lang: fr-FR


#
# Jekyll Settings
#

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

feed:
  path: atom.xml

kramdown:
  syntax_highlighter_opts:
    disable : true
